version: "3"
services:
  node-webapi:
    image: 000341004250.dkr.ecr.eu-west-2.amazonaws.com/node-webapi:1.3
    ports:
      - 5000:3000
    environment:
      - USER="gnutz"
      - PASSWORD="kaansdpe19"
      - NODE_ENV=development
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - 5672:5672
      - 15672:15672
  rmq-student-write:
    image: 000341004250.dkr.ecr.eu-west-2.amazonaws.com/rmq-students-write:1.1
    ports:
      - 4000:3000
    environment:
      - USER="gnutz"
      - PASSWORD="kaansdpe19"
